Spring Dependency Injection implementation
mwrobert/invoicing-system-robert-wojtaszek pull request #13
Opened 2022-09-08 18:58 UTC by mwrobert

Please review and merge with master.

2022-09-11 19:21 UTC, patryk-stepniak requested changes
Jedna uwaga

2022-09-11 19:21 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/configuration/InvoiceBeanConfiguration.java
>    public static final Path ID_PATH = Paths.get("db-prod/nextid.txt");
To nie powinno być publiczne.

2022-09-11 19:21 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/configuration/InvoiceBeanConfiguration.java
> +    return new InFileDatabase(jsonMapper(), fileService(), DB_PATH, ID_PATH);
Super

2022-09-11 19:38 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/configuration/InvoiceBeanConfiguration.java
>    public static final Path ID_PATH = Paths.get("db-prod/nextid.txt");
Zmieniłem access level z public na default (package)

2022-09-17 14:46 UTC, patryk-stepniak approved these changes

2022-09-17 14:46 UTC, merged