Project setup with Jacoco, Github actions and Lombok
mwrobert/invoicing-system-robert-wojtaszek pull request #5
Opened 2022-08-08 18:52 UTC by mwrobert

Updated project to include support for Jacoco, Lombok and Github actions.
Please review and merge with master branch.

2022-08-11 12:05 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/App.java
> +    } catch (IllegalArgumentException e) {
Na przyszłość: IllegalArgumentException nie jest czymś to chcielibyśmy obsługiwać. Tego typu błędów staramy się po prostu unikać :)

2022-08-11 12:06 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/Database.java
> +  void update(long id, Invoice updatedInvoice);
Nazwa argumentu "updatedInvoice" sugeruje, że został on już zaktualizowany.

2022-08-11 12:07 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/model/Company.java
> +public class Company {
Tutaj przydały by się jakieś gettery, by klasa miała rację bytu :)

2022-08-11 12:08 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/model/Invoice.java
> +public class Invoice {
Tutaj przydały by się jakieś gettery, by klasa miała rację bytu :)

2022-08-11 12:08 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
> +public class InvoiceEntry {
Tutaj przydały by się jakieś gettery, by klasa miała rację bytu :)

2022-08-11 12:08 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/model/Vat.java
> +    BigDecimal rate1 = BigDecimal.valueOf(rate);
Co to?

2022-08-11 12:09 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +  public void update(long id, Invoice updateInvoice) {
"updateInvoice" - to samo co w interfejsie

2022-08-11 13:38 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/model/Company.java
> +public class Company {
Przyznaje bez bicia, że zrezygnowałem z getterów aby usatysfakcjonować Jococo...

2022-08-11 14:13 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/model/Vat.java
> +    BigDecimal rate1 = BigDecimal.valueOf(rate);
bezmyślne kopiowanie i to i błedami...
Porwałem constructor, i dodałem getRate method

2022-08-11 14:26 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +  public void update(long id, Invoice updateInvoice) {
poprawiłem na invoiceToUpdate

2022-08-11 14:26 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/Database.java
> +  void update(long id, Invoice updatedInvoice);
poprawiłem na invoiceToUpdate

2022-08-11 14:27 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/App.java
> +    } catch (IllegalArgumentException e) {
Zmeiniłem na RuntimeException jak na lekcjii :)

2022-08-13 06:29 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/App.java
> +    } catch (IllegalArgumentException e) {
Chodziło mi o to, że wszystkie wyjątki unchecked (rozszerzające RuntimeException) są wyjątkami, których nie obsługujemy. Teoretycznie możemy i pewnie znajdzie się jakiś przykład, gdzie lepiej je obsłużyć, jednak z reguły są to wyjątki, których nie obsługujemy, ponieważ nie wiemy jak (z biznesowego punktu widzenia) i chcemy aby w konkretnych warunkach występowały.

2022-08-13 06:33 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/App.java
> +    } catch (IllegalArgumentException e) {
W tym konkretnym przypadku użylibyśmy EntityNotFoundException, ale z tego co widzę to nie macie go w projekcie. Proponuję go utworzyć samemu. Ostatecznie IllegalArgumentException może zostać.

Na wykładzie było RuntimeException wyłącznie dla przykładu.

2022-08-13 06:38 UTC, patryk-stepniak commented
Wygląda dobrze.
Pozostaje jedynie kwestia wyjątku. Tutaj możesz zostawić IllegalArgumentException, jednak proponowałbym Ci zrobić nowy wyjątek EntityNotFoundException. Twój wybór

2022-08-13 06:38 UTC, patryk-stepniak requested changes
Wygląda dobrze.
Pozostaje jedynie kwestia wyjątku. Tutaj możesz zostawić IllegalArgumentException, jednak proponowałbym Ci zrobić nowy wyjątek EntityNotFoundException. Twój wybór

2022-08-13 13:38 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/App.java
> +    } catch (IllegalArgumentException e) {
Dodałem klasę EntityNotFoundException i zaktualizowałem PR

2022-08-16 11:54 UTC, patryk-stepniak approved these changes

2022-08-16 11:55 UTC, merged