Implementation of database storing invoices as JSON in file.
mwrobert/invoicing-system-robert-wojtaszek pull request #7
Opened 2022-08-17 22:00 UTC by mwrobert

Please review and merge with master

2022-08-19 13:11 UTC, patryk-stepniak requested changes

2022-08-19 13:11 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/Configuration.java
> +  public static final String ID_FILE = "nextid.txt";
Wrzuciłbym te pliki do osobnego folderu (np. db), aby nie robić bałaganu w głownej lokalizacji.

2022-08-19 13:11 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +      throw new RuntimeException(e);
Dorzuć informację o obiekcie, dla którego wystąpił wyjątek.

2022-08-19 13:11 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +        throw new RuntimeException(e);
Tutaj również lepiej będzie dodać informacje o id'ku, dla którego chcesz wykonać update.

2022-08-19 13:11 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    for (Invoice invoice : allInvoices) {
Za długa metoda. Wydziel część do osobnej prywatnej metody, dzięki czemu będzie łatwiej zrozumieć co się tutaj dzieje.
Podobnie w pozostałych metodach publicznych.

2022-08-19 13:11 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
>  public class InvoiceEntry {
Rzuć okiem na adnotację @Data. Może się przydać (ale nie musi).

2022-08-19 13:11 UTC, patryk-stepniak commented on src/test/groovy/pl/futurecollars/invoicing/db/file/FileServiceTest.groovy
> +    def "should replace file content with multiple lines on writeAllLines call"() {
Fakt, że given/when/then występuje dwukrotnie może oznaczać, że test sprawdza dwie rzeczy. To nie jest ten przypadek, jednak lepiej przerobić ten test, by posiadał tylko jedno given/when/then.

2022-08-20 20:42 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/App.java
> +    Database db = InFileDatabase.builder()
Zrezygnowałem z buildera i zrobiłem konstruktor.

2022-08-20 20:44 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/Configuration.java
> +  public static final String ID_FILE = "nextid.txt";
Nazwa pliku bazy dany zmieniona database.json

2022-08-20 20:44 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +      throw new RuntimeException(e);
Zmienine

2022-08-20 20:46 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +        throw new RuntimeException(e);
Zmienione na RuntimeException("Problem deleting invoice with Id = " + id, e)

2022-08-20 20:49 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    for (Invoice invoice : allInvoices) {
Nie wydzieliłem bo zamieniłem for() na stream() processing więc może teraz wygląda lepiej (bardziej zrozumiale)

2022-08-20 20:49 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
>  public class InvoiceEntry {
Zastąpiłem @Data'a

2022-08-20 20:53 UTC, mwrobert commented on src/test/groovy/pl/futurecollars/invoicing/db/file/FileServiceTest.groovy
> +    def "should replace file content with multiple lines on writeAllLines call"() {
Zmienione

2022-08-22 08:06 UTC, patryk-stepniak requested changes
Kilka drobnych uwag

2022-08-22 08:06 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/JsonMapper.java
> +    this.jsonMapper = new ObjectMapper();
Jeśli zdecydowałeś się na wstrzykiwanie zależności (słusznie!) to tego konstruktora bym się pozbył.

2022-08-22 08:06 UTC, patryk-stepniak commented on src/test/groovy/pl/futurecollars/invoicing/db/file/InFileDatabaseTest.groovy
> +        def fileService = Mock(FileService)
Jeżeli w większości testów musisz tworzyć jakiś obiekt, to może warto wynieść to tworzenie to metody setup?

2022-08-22 09:45 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/Configuration.java
> +  public static final String ID_FILE = "db/nextid.txt";
Nie za bardzo rozumiem bo obecnie Configuration posiada:
 public static final String ID_FILE = "db/nextid.txt";
 public static final String DATABASE_FILE = "db/database.json";

Baza danych jest w formacie json (kind of) a nextId w txt

2022-08-24 06:18 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/Configuration.java
> +  public static final String ID_FILE = "db/nextid.txt";
Dokładnie o to chodziło, jest ok :)

2022-08-27 08:50 UTC, patryk-stepniak requested changes
Kilka uwag

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    // Opening Id repository
Zamiast dodawać komentarze wydziel kod do osobnej metody, której nazwa będzie mówić co robi dany kod.

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    // initializing database repository
jak wyżej

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    List<Invoice> allInvoices = new ArrayList<>();
Całą metodę można zapisać jako stream.

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    List<String> jsonList;
jak wyżej

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +      List<Invoice> updatedInvoices = getAll().stream()
Zamiast tworzyć dwie niemal identyczne listy (które mogą być długie) - jednej w metodzie getAll(), a drugiej tutaj,
na liście zwracanej przez getAll() znajdź element, który chcesz zupdate'ować, zdeserializuj go, ustaw mu pola na odpowiednie wartości, zserializuj, wrzuc ponownie na liste zwrocona przez getAll() i zapisz tę listę do pliku.

Nie chcemy mieć dwóch potencjalnie dużych list różniących się tylko jednym elementem.

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +      try {
Analogiczny blok try-catch znajduje się kilka razy w tej metodzie. Może warto go wynieść do osobnej metody?

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/JsonMapper.java
> +  public JsonMapper(ObjectMapper jsonMapper) {
Super

2022-08-27 08:50 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/JsonMapper.java
> +    List<String> allInvoices = new ArrayList<>();
Spróbuj zapisać to przy pomocy streama

2022-08-30 17:05 UTC, patryk-stepniak requested changes
Kilak rzeczy do poprawy.

2022-08-30 17:05 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +              .map(invoice -> invoice.getId() == id ? invoiceToUpdate : invoice)
Przy update'cie nie chcemy podmieniać całego obiektu, a raczej zaktualizować dane na obiekcie już znajdującym się w bazie danych.

Znajdź interesujący cię obiekt, przy pomocy seterów ustaw mu odpowiednie pola, a następnie zapisz w bazie.

2022-08-30 17:05 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    if (getById(id).isPresent()) {
Metoda getById pobiera listę wszystkich obiektów i zaraz w metodzie updateAndSave robisz to ponownie.

2022-08-30 17:05 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    if (getById(id).isPresent()) {
Jedna lista w metodzie getById, druga w getAll.
Analogicznie jak przy update'cie.

2022-08-31 09:58 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/FileService.java
> +  public void createRepository(Path path) throws IOException {
- zmiana nazwy metody createRepository na createFile 
  - zmaina metody createFile aby używała obiekt typu Path

2022-08-31 09:59 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    openIdRepo();
- zmina nazwy metody createIdRepo na initializeIdRepo
- zmina nazwy metody createDbRepo na initializeDbRepo

2022-08-31 10:01 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    try {
Utworzyłem metodę updateIdRepo

2022-08-31 10:02 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +  private void updateIdRepo(long l) {
Zastąpiłem metodą updateIdRepo

2022-08-31 10:04 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +          .map(jsonMapper::invoiceFromJson)
Zmieniłem na:
.filter(line -> jsonMapper.invoiceFromJson(line).getId() == id)
.map(jsonMapper::invoiceFromJson)
.findFirst();

2022-08-31 10:06 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +      updateAndSave(id, invoiceToUpdate);
Storzyłem 2 metody:
- updateInvoice
- saveAllInvoices

2022-08-31 10:09 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +              .map(invoice -> invoice.getId() == id ? invoiceToUpdate : invoice)
Utworzyłem metodę updateInvoice

2022-08-31 10:10 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    if (getById(id).isPresent()) {
Poprawiłem aby tylko raz pobierać listę obiektów za bazy danych

2022-08-31 10:11 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    if (getById(id).isPresent()) {
Poprawione

2022-09-03 16:43 UTC, patryk-stepniak requested changes
Kilka uwag.

2022-09-03 16:43 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +  private void saveAllInvoices(long id, List<Invoice> allInvoices) {
Parametr Id wydaje się być tutaj zbędnym. Metoda zajmuje się zapisem wszystkich Invoice'ów, a wyjątek mówi o problemie z zapisem jednego.

Wiem co chcesz osiągnąć. Spróbuj nie łapać wyjątku w tej metodzie, a dopiero w metodzie wyżej. Tam gdzie faktycznie aktualizujesz jeden obiekt.

2022-09-03 16:43 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    for (Invoice invoice : allInvoices) {
Dobrze :)

Ale zatrzymaj pętle w momencie, gdy już znajdzie poszukiwany element.

2022-09-03 16:43 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    try {
Nazwy można by poprawić.

Tak naprawdę updateXYZRepo nie wiele mówi.
To co faktycznie chcesz zrobić to
1. Zapisać invoice w bazie
2. Podbić Id
więc sugeruję dobrać nazwy według tego, ponieważ pod określeniem "update repo" może się kryć wiele rzeczy.
Samo to, że tutaj te nazwy są niemal identyczne, a realizują zupełnie inne biznesowe funkcjonalności świadczy o tym, że coś jest nie tak.

2022-09-03 16:43 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/FileService.java
> +    writeLine(path, "");
Średnio mi się podoba, że chcąc utworzyć plik, zapisujesz coś do niego.
Ale niech będzie.

2022-09-04 17:28 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +  private void saveAllInvoices(long id, List<Invoice> allInvoices) {
Poprawiłem i łapie wyjątek w metodzie, która woła tę w której może wystąpić wyjątek

2022-09-04 17:29 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +    for (Invoice invoice : allInvoices) {
break in place

2022-09-04 17:30 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/FileService.java
> +    writeLine(path, "");
Już zapomniałem co autor miał na myśli uciekając się do tej kombinacji...
Zmieniłem na Files.createFile(path);

2022-09-05 17:46 UTC, patryk-stepniak requested changes
Generalnie wygląda ok.
Moglibyśmy jeszcze podyskutować o nazwach metod, czy rozmieszczeniu kodu, ale będzie na to czas na następnej lekcji z clean code'u.

Wrzuciłem Ci jedną uwagę. Popraw to proszę i lecimy z mergem i kolejnymi zadaniami :)

2022-09-05 17:46 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +          .filter(line -> jsonMapper.invoiceFromJson(line).getId() == id)
Dopiero teraz zauważyłem tę zmianę.
Nie wniosła ona niczego, ponieważ za każdym razem mapujesz wszystkie obiekty, a później jeszcze jeden raz mapujesz ten, którego szukasz.

To już wróćmy do poprzedniego rozwiązania, gdzie najpierw mapujesz wszystkie elementy, a później filtrujesz.

2022-09-05 17:47 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +          .filter(line -> jsonMapper.invoiceFromJson(line).getId() == id)
Można by pokombinować w inny sposób, ale nie jest to konieczne.

2022-09-05 18:39 UTC, mwrobert commented on src/main/java/pl/futurecollars/invoicing/db/file/InFileDatabase.java
> +          .filter(line -> jsonMapper.invoiceFromJson(line).getId() == id)
zmieniłem na:
.map(jsonMapper::invoiceFromJson)
.filter(inv -> inv.getId() == id)
.findFirst();

2022-09-07 07:31 UTC, patryk-stepniak approved these changes

2022-09-07 07:31 UTC, merged